import { Providers } from '@/app/Providers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="red-light dark:red-dark min-h-screen bg-[#fffffe] pb-8 text-[#101010] dark:bg-[#101010] dark:text-[#d4d4d4]">
            <div className="red-light dark:red-dark px-6">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
